title: Chaewon Baek
author:
  name: Chaewon Baek
  email: cwb1207@snu.ac.kr
description: >
  Undergraduate Student at Seoul National University
#google_analytics_id: UA-215543768-1

show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:title

url: "https://kaygon.github.io" # the base hostname & protocol for your site

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-SVM0FPLQHK"
    anonymize_ip         : # true, false (default)